### ISSUE TITLE
Was this a one off?

### ISSUE THREAD

**Issue by rossmuir** [matthew-davis/northayrshireopendatahack#1]
Hi,

Was this event a one off or a series of events? I unfortunately missed this one as I was away at the time and just catching up.

Cheers
Ross

**Comment by matthew-davis** [comment]
That particular event was a one off. However I believe that North Ayrshire
is committed to doing something moving forward in the new year.

Best,

Matthew

**Comment by rossmuir** [comment]
Thank you I will keep my ear to the ground.
